### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

### ISSUE THREAD

**Issue by joname1** [eqblog/91_porn_spider#1]
编码也换了utf-8，还是报错！
<img width="570" alt="20180209-154653 2x" src="https://user-images.githubusercontent.com/15252214/36017069-1eb2874a-0db1-11e8-9245-119601e1442c.png">

**Comment by eqblog** [comment]
系统环境变量问题 export LANG=en_US.UTF-8
