### ISSUE TITLE
index out of range?

### ISSUE THREAD

**Issue by xwjBupt** [eqblog/91_porn_spider#17]
```
traceback (most recent call last):
  File "91_spider.py", line 32, in <module>
    bases_req = requests.get(ifm[0], headers=headers)
IndexError: list index out of range
```

刚爬了一下就不行了?期待解决,十分感谢!

**Comment by beidouchain005outlook** [comment]
@xwjBupt 在bases_req = requests.get(ifm[0], headers=headers)（49行左右）的上边加上

if len(ifm) == 0:
            continue

就可以了

**Comment by deemoartisan** [comment]
> @xwjBupt 在bases_req = requests.get(ifm[0], headers=headers)（49行左右）的上边加上
> 
> if len(ifm) == 0:
> continue
> 
> 就可以了

老哥，还是不行啊。。求教
