### ISSUE TITLE
91新增加了Cloudflare的验证

### ISSUE THREAD

**Issue by zzxyangzhou** [eqblog/91_porn_spider#21]
<Response [403]>

**Comment by zzzop** [comment]
不好弄了吧

**Comment by zzxyangzhou** [comment]
更新了吗？

eqblog <notifications@github.com>于2019年12月19日 周四下午9:54写道：

**Comment by eqblog** [comment]
已经在新版本解决了此问题，但需要配合anti-captcha.com账户使用。

相当于付费打码。

**Comment by zzxyangzhou** [comment]
好的，明天试一下。我之前用你的脚本撸到了2017年左右的视频，3、4个TB的视频都在了Google Cloud Storage。

eqblog <notifications@github.com>于2019年12月19日 周四下午9:58写道：
